In [2]:
import numpy as np

In [4]:
a = np.zeros((2,2),dtype="int32")

In [5]:
a

array([[0, 0],
       [0, 0]], dtype=int32)

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.random.randint(9,size=(3,3))

array([[2, 6, 2],
       [6, 8, 1],
       [7, 2, 4]], dtype=int32)

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
a = np.arange(1,6)
a*3

array([ 3,  6,  9, 12, 15])

In [28]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6,])

In [29]:
a1+a2

array([5, 7, 9])

In [30]:
rand_3x3 = np.random.randint(100,size=(3,3))

In [31]:
rand_3x3

array([[96, 88, 38],
       [24, 91, 55],
       [16, 18,  7]], dtype=int32)

In [47]:
rand_3x3[ 1 ]

array([24, 91, 55], dtype=int32)

In [48]:
arr = np.arange(1,11)

In [49]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[arr%2 ==0]

array([ 2,  4,  6,  8, 10])

In [67]:
arr =np.random.randint(1,100,size=(5,5))
print(arr)

[[96 80 60 22 15]
 [16 81 10  6 49]
 [63 99 54 52 56]
 [74 32 71 60 66]
 [26 18 59  6 80]]


In [68]:
print(arr.max())
print(arr.min())
print(arr.mean())

99
6
50.04


In [70]:
arr = np.arange(1,13)
arr.shape

(12,)

In [74]:
reshaped = arr.reshape((3,4))

In [83]:
reshaped.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
arr = np.array([10,20,30,40,50])

In [85]:
arr[arr>25]

array([30, 40, 50])

In [86]:
mat1 = np.random.randint(100,size=(3,3))
mat2 = np.random.randint(100,size=(3,3))

In [92]:
np.linalg.det(mat1)


np.float64(-170776.00000000017)

In [93]:
mat1 = np.random.randint(100,size=(3,3))

In [95]:
print(mat1)
mat1 + [1,2,3]

[[82 20 26]
 [24 12 74]
 [10 77 44]]


array([[83, 22, 29],
       [25, 14, 77],
       [11, 79, 47]])