In [2]:
import numpy as np

In [3]:
arr_temp = np.arange(1,31)
arr = arr_temp.reshape((6,5))

In [4]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [5]:
arr[ 2:4,0:2 ]

array([[11, 12],
       [16, 17]])

In [6]:
arr[ 0:4, 1:5:1 ]*np.identity(4)

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  8.,  0.,  0.],
       [ 0.,  0., 14.,  0.],
       [ 0.,  0.,  0., 20.]])

In [7]:
arr[ [0,1,2,3],[1,2,3,4] ] 

array([ 2,  8, 14, 20])

In [8]:
arr[ [0,4,5],3:5  ] 

array([[ 4,  5],
       [24, 25],
       [29, 30]])